#!/bin/bash
set -e

echo "🧪 Simulating GitHub Actions Build Process..."
echo ""

# Clean up node_modules and prisma client to simulate fresh CI environment
echo "🧹 Cleaning up (simulating fresh CI environment)..."
rm -rf node_modules/.pnpm/@prisma+client* 2>/dev/null || true
rm -rf node_modules/.prisma 2>/dev/null || true

echo ""
echo "📦 Step 1: Installing dependencies (with postinstall hook)..."
pnpm install --frozen-lockfile

echo ""
echo "🔍 Step 2: Checking if Prisma Client was generated by postinstall..."
if [ -d "node_modules/.pnpm/@prisma+client@7.2.0_prisma@7.2.0_@types+react@19.2.7_react-dom@19.2.3_react@19.2.3__react@19.2.3__/node_modules/@prisma/client" ]; then
    echo "✅ Prisma Client generated successfully by postinstall!"
else
    echo "❌ Prisma Client NOT found after postinstall"
    exit 1
fi

echo ""
echo "🏗️  Step 3: Running build (prisma generate && next build)..."
pnpm build

echo ""
echo "✅ All steps completed successfully!"
echo "This simulates what GitHub Actions would do."
